config/routes.rb
Rails.application.routes.draw do
  #get 'books/new'
  #get '/top' => 'homes#top'
  root 'homes#top'
  #post 'books' => 'books#create'
  #get 'books' => 'books#index'
  #get 'books/:id' => 'books#show'
  resources :books
  get 'books/:id' => 'books#show'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book_path'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new

  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:success] = 'Book was successfully created.'
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index

    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if  @book.update(book_params)
      flash[:success] = 'Book was successfully updated.'
      redirect_to book_path(@book.id)
    else
      @books = Book.find(params[:id])
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'

  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this book from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
<% end %>


<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Update Book' %>

<% end %>

<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<html>
  <head>

  <body>
    <p id="notice"></p>
    <h1>Books</h1>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
         <% @books.each do |book| %>
           <tr>
             <td>
                <%= book.title %>
             </td>
             <td>
                <%= book.body %>
             </td>
             <td>
               <%= link_to "Show", book_path(book) %>
             </td>
             <td>
               <%= link_to "Edit", edit_book_path(book) %>
             </td>
             <td>
               <%= link_to "Destroy", book_path(book), method: :delete, "data-confirm" => "本当に削除しますか？" %>

             </td>
           </tr>
         <% end %>
      </tbody>
    </table>
    <h2>New book</h2>

    <% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this book from being saved:
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_with model: @book do |f| %>
      <h4>タイトル</h4>
      <%= f.text_field :title %>
      <h4>本文</h4>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book' %>
    <% end %>
  </body>
</html>

app/views/books/new.html.erb
<h1>新規投稿</h1>
<h1>Books</h1>
    <% if @book.errors.any? %>
      <%= @book.errors.count %>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
<%= form_with model: @book do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<%= flash[:success] %>

<p><strong>Title:</strong> <%= @book.title %></p>
<p><strong>Body:</strong> <%= @book.body %></p>

<%#= link_to "削除", books_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

<%= link_to "Edit", edit_book_path(@book.id) %>
|
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <body>
    <h1>ようこそ
    <strong>Bookers</strong>
    へ!
    </h1>
    <p>
      <strong>Bookers</strong>
      では、さまざまな書籍に関するあなたの意見や
    </p>
    <p>印象を共有し交換することができます</p>
    <%= link_to "start",books_path %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>